const DEFAULTS=[{name:'拉面',emoji:'🍜'},{name:'寿司',emoji:'🍣'},{name:'烤肉',emoji:'🥩'},{name:'汉堡',emoji:'🍔'},{name:'披萨',emoji:'🍕'},{name:'火锅',emoji:'🍲'}];
const KEY='kikoFoodRoulette6';
let foods=load(),rotation=0,spinning=false;
const wheel=document.getElementById('wheel'),rotator=document.getElementById('rotator'),labels=document.getElementById('labels');
const result=document.getElementById('result'),resultEmoji=document.getElementById('resultEmoji'),resultName=document.getElementById('resultName');
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(Array.isArray(x)&&x.length===6)return x;}catch(e){}return DEFAULTS.map(x=>({...x}));}
function draw(){const c=wheel.getContext('2d'),n=6,s=wheel.width,r=s/2-10,a=Math.PI*2/n,colors=['#fff0ad','#ffc6de','#aee2ff','#ffd9a8','#b7f1dc','#ffc4dc'];c.clearRect(0,0,s,s);for(let i=0;i<n;i++){let st=-Math.PI/2-a/2+i*a;c.beginPath();c.moveTo(s/2,s/2);c.arc(s/2,s/2,r,st,st+a);c.closePath();c.fillStyle=colors[i];c.fill();c.strokeStyle='#fff';c.lineWidth=6;c.stroke();}c.beginPath();c.arc(s/2,s/2,92,0,Math.PI*2);c.fillStyle='#ff8caf';c.fill();c.strokeStyle='#fff';c.lineWidth=8;c.stroke();}
function render(){labels.innerHTML='';foods.forEach((f,i)=>{const el=document.createElement('div');el.className='label';el.innerHTML=`<div class="label-inner"><span class="emoji">${f.emoji}</span><span class="name">${f.name}</span></div>`;labels.appendChild(el)});position();counter(rotation)}
function position(){const s=rotator.clientWidth,c=s/2,r=s*.34;[...labels.children].forEach((el,i)=>{let a=(-90+i*60)*Math.PI/180;el.style.left=c+Math.cos(a)*r+'px';el.style.top=c+Math.sin(a)*r+'px'})}
function counter(deg){document.querySelectorAll('.label-inner').forEach(x=>x.style.transform=`rotate(${-deg}deg)`)}
function spin(){if(spinning)return;spinning=true;document.getElementById('go').disabled=true;const win=Math.floor(Math.random()*6),start=rotation,target=start+360*5+(360-(win*60));rotation=target;rotator.style.transform=`rotate(${target}deg)`;document.querySelectorAll('.label-inner').forEach(x=>x.animate([{transform:`rotate(${-start}deg)`},{transform:`rotate(${-target}deg)`}],{duration:5000,easing:'cubic-bezier(.12,.72,.16,1)',fill:'forwards'}));setTimeout(()=>{spinning=false;document.getElementById('go').disabled=false;counter(rotation);resultEmoji.textContent=foods[win].emoji;resultName.textContent=foods[win].name;result.classList.remove('hidden')},5050)}
function openEditor(){const box=document.getElementById('inputs');box.innerHTML='';foods.forEach((f,i)=>{const row=document.createElement('div');row.className='food-row';row.innerHTML=`<input class="icon" maxlength="4" value="${f.emoji}"><input class="foodname" maxlength="10" value="${f.name}">`;box.appendChild(row)});document.getElementById('editor').classList.remove('hidden')}
function save(){foods=[...document.querySelectorAll('.food-row')].map((r,i)=>({emoji:r.querySelector('.icon').value.trim()||DEFAULTS[i].emoji,name:r.querySelector('.foodname').value.trim()||DEFAULTS[i].name}));localStorage.setItem(KEY,JSON.stringify(foods));render();draw();document.getElementById('editor').classList.add('hidden')}
document.getElementById('go').onclick=spin;document.getElementById('again').onclick=()=>{result.classList.add('hidden');setTimeout(spin,120)};document.getElementById('home').onclick=()=>result.classList.add('hidden');document.getElementById('editBtn').onclick=openEditor;document.getElementById('closeEditor').onclick=()=>document.getElementById('editor').classList.add('hidden');document.getElementById('save').onclick=save;window.onresize=position;draw();render();
